config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :assignments

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  def index
    @assignments = Assignment.all
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)

    if @assignment.save
      redirect_to @assignment
    else
      render 'new'
    end
  end

  def update
    @assignment = Assignment.find(params[:id])

    if @assignment.update(assignment_params)
      redirect_to @assignment
    else
      render 'edit'
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

  def destroy
    @assignment = Assignment.find(params[:id])
    if @assignment.delete
      flash[:notice] = 'Assignment deleted!'
      redirect_to assignments_path
    else
      flash[:error] = 'Failed to delete assignment!'
      render :destroy
    end
  end

  private
  def assignment_params
    params.require(:assignment).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignment_helper.rb
module AssignmentHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assignments/_form.html.erb
<%= form_with model: @assignment, local: true, data: { turbo: false} do |form| %>

  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@assignment.errors.count, "error") %> prohibited
        this assignment from being saved:
      </h2>
      <ul>
        <% @assignment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/assignments/edit.html.erb
<h1>Edit assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing Assignments</h1>

<%= link_to 'New assignment', new_assignment_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @assignments.each do |assignment| %>
    <tr>
      <td><%= assignment.title %></td>
      <td><%= assignment.text %></td>
      <td><%= link_to 'Show', assignment_path(assignment) %></td>
      <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
      <td><%= link_to 'Destroy', assignment_path(assignment),
      data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %></td>
    </tr>
  <% end %>
</table>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path%>

app/views/assignments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @assignment.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @assignment.text %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Assignment', controller: 'assignments' %>